CREATE DATABASE projetologin;

USE projetologin;

CREATE TABLE usuario(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    email CHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL
);